---
version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8080
    volumes:
      - ${PWD}/qbittorrent/config:/config
      - ${PWD}/storage/downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ${PWD}/sonarr/config:/config
      - ${PWD}/storage/tvseries:/tv #optional
      - ${PWD}/storage/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ${PWD}/radarr/config:/config
      - ${PWD}/storage/movies:/movies #optional
      - ${PWD}/storage/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - AUTO_UPDATE=true #optional
#      - RUN_OPTS=<run options here> #optional
    volumes:
      - ${PWD}/jackett/config:/config
      - ${PWD}/storage/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex
    container_name: plexmediaserver
#    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - ${PWD}/plex/config:/config
      - ${PWD}/storage/tv:/tv
      - ${PWD}/storage/movies:/movies
    ports:
      - 32400:32400/tcp
      - 1900:1900/udp
      - 3005:3005
      - 5353:5353/udp
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    restart: unless-stopped
